media:
  input: media/banners
  output: /media/banners

content:
  - name: banners
    label: Marketplace Banners
    type: collection
    path: data/banners
    format: json
    fields:
      - name: id
        label: Banner ID / Slug
        type: string
      - name: image
        label: Banner Image
        type: image
      - name: targetUrl
        label: Clickable URL
        type: string
      - name: altText
        label: Alt Text
        type: string
      - name: order
        label: Display Order
        type: number
      - name: active
        label: Active?
        type: boolean
        default: true
